CREATE PROC  SP_Print_PHIEUDIEM
@NHOM nvarchar(10),
@MASV char(12)
AS
BEGIN
	DECLARE @tempTable table(STT int, MAMH char(6), DIEM float)
	INSERT INTO @tempTable SELECT ROW_NUMBER() OVER(ORDER BY MAMH asc) AS STT, MAMH, MAX(DIEM) AS DIEM FROM DIEM WHERE DIEM.MASV = '09THA103' GROUP BY MAMH
	if(@NHOM = 'PGV')
	BEGIN
		INSERT INTO @tempTable SELECT ROW_NUMBER() OVER(ORDER BY MAMH asc) AS STT, MAMH, MAX(DIEM) AS DIEM FROM KHOA_LINKED.QLDSV.dbo.DIEM WHERE DIEM.MASV = '09THA103' GROUP BY MAMH
		union 
		SELECT * FROM @tempTable;
	END
	SELECT * FROM @tempTable
END