CREATE PROC SP_List_LOP
@NHOM nvarchar(10)
AS
BEGIN
	DECLARE @tempTableLOP table(MALOP char(8),TENLOP nvarchar(200))
	INSERT INTO @tempTableLOP SELECT MALOP, TENLOP FROM LOP
	if(@NHOM = 'PGV')
		SELECT * FROM @tempTableLOP union SELECT MALOP, TENLOP FROM KHOA_LINKED.QLDSV.dbo.LOP
	ELSE
	SELECT * FROM @tempTableLOP
END