CREATE PROC SP_Print_SINHVIEN
@NHOM nvarchar(10),
@MALOP char(8)
AS
BEGIN
	DECLARE @tempTableSINHVIEN table(MASV char(12) NOT NULL,
	HO nvarchar(40) NULL,
	TEN nvarchar(10) NULL,
	PHAI nvarchar(3) NULL,
	NGAYSINH datetime NULL,
	NOISINH nvarchar(40) NULL,
	DIACHI nvarchar(80) NULL);

	INSERT INTO @tempTableSINHVIEN 
		SELECT MASV, HO, TEN, 
			CASE PHAI WHEN 0 THEN 'Nu'
					  WHEN 1 THEN 'Nam'
			END AS PHAI,
			NGAYSINH, NOISINH, DIACHI FROM SINHVIEN WHERE SINHVIEN.MALOP = @MALOP;
	if(@NHOM = 'PGV' AND @NHOM = 'KETOAN')
	begin
		INSERT INTO @tempTableSINHVIEN 
		SELECT MASV, HO, TEN, 
			CASE PHAI WHEN 0 THEN 'Nu'
					  WHEN 1 THEN 'Nam'
			END AS PHAI,
			NGAYSINH, NOISINH, DIACHI FROM KHOA_LINKED.QLDSV.dbo.SINHVIEN WHERE SINHVIEN.MALOP = @MALOP
		UNION SELECT * FROM @tempTableSINHVIEN;
	end
	SELECT * FROM @tempTableSINHVIEN;
END