CREATE PROC SP_Print_BANGDIEM_TONGKET_2
@NHOM nvarchar(10),
@MALOP char(8)
AS
BEGIN
	DECLARE @Return table(MASV_HOTEN nvarchar(60), TENMH nvarchar(40), DIEM float);
	DECLARE @tempTableDIEM_LOP table(MASV_HOTEN nvarchar(60), TENMH nvarchar(40), LAN smallint, DIEM float);
	
	INSERT INTO @tempTableDIEM_LOP 
	SELECT RTRIM(DIEMSV.MASV)+'-'+DIEMSV.HOTEN, MONHOC.TENMH, DIEMSV.LAN, DIEMSV.DIEM FROM
		(SELECT dbo.DIEM.MASV, tableSV.HOTEN,  dbo.DIEM.MAMH, dbo.DIEM.LAN, dbo.DIEM.DIEM
			FROM (dbo.DIEM inner join (SELECT MASV, HO+' '+TEN AS HOTEN FROM SINHVIEN WHERE MALOP = @MALOP) AS tableSV 
				ON (dbo.DIEM.MASV = tableSV.MASV))) AS DIEMSV 
		inner join MONHOC ON DIEMSV.MAMH = MONHOC.MAMH
	INSERT INTO @Return
		SELECT MASV_HOTEN, TENMH, Max(DIEM) as DIEM 
			FROM @tempTableDIEM_LOP GROUP BY MASV_HOTEN, TENMH

	if(@NHOM = N'PGV')
		begin
			DECLARE @tempTableDIEM_LOP_LINKED table(MASV_HOTEN nvarchar(52), TENMH nvarchar(40), LAN smallint, DIEM float);
	
			INSERT INTO @tempTableDIEM_LOP_LINKED 
			SELECT RTRIM(DIEMSV.MASV)+'-'+DIEMSV.HOTEN, MONHOC.TENMH, DIEMSV.LAN, DIEMSV.DIEM FROM
				(SELECT LINKED_DIEM.MASV, tableSV.HOTEN,  LINKED_DIEM.MAMH, LINKED_DIEM.LAN, LINKED_DIEM.DIEM
					FROM (KHOA_LINKED.QLDSV.dbo.DIEM AS LINKED_DIEM inner join (SELECT MASV, HO+' '+TEN AS HOTEN FROM KHOA_LINKED.QLDSV.dbo.SINHVIEN WHERE MALOP = @MALOP) AS tableSV 
						ON (LINKED_DIEM.MASV = tableSV.MASV))) AS DIEMSV 
			inner join MONHOC ON DIEMSV.MAMH = MONHOC.MAMH
			
			SELECT MASV_HOTEN, TENMH, Max(DIEM) as DIEM 
				FROM @tempTableDIEM_LOP_LINKED GROUP BY MASV_HOTEN, TENMH
			UNION SELECT * FROM @Return;
		end
		else
			SELECT * FROM @Return
END