CREATE PROC SP_Print_DS_DONGHOCPHI
@MALOP char(8),
@NIENKHOA nvarchar(50),
@HOCKY INT
AS
BEGIN
	DECLARE @tempTableSINHVIEN table(MASV char(12) NOT NULL,HOTEN nvarchar(50) NULL);
	INSERT INTO @tempTableSINHVIEN 
		SELECT MASV, (HO +' '+TEN) AS HOTEN FROM SINHVIEN WHERE SINHVIEN.MALOP = @MALOP;
	SELECT ROW_NUMBER() OVER(ORDER BY MASV asc) AS STT, * 
		FROM (SELECT tableSINHVIEN.MASV , tableSINHVIEN.HOTEN, HOCPHI.HOCPHI, HOCPHI.SOTIENDADONG FROM @tempTableSINHVIEN as tableSINHVIEN inner join dbo.HOCPHI ON tableSINHVIEN.MASV = dbo.HOCPHI.MASV) tableHOCPHI;
END

